# Generated by Django 5.1.1 on 2024-11-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_profile_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_wishlist',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
