# Generated by Django 5.1.1 on 2024-11-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_covers/'),
        ),
    ]
