# Generated by Django 5.1.4 on 2025-02-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_skintype_product_skin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
