# Generated by Django 5.1.4 on 2025-02-07 03:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_description2_product_description3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description3',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
